services:
  autodidact:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Mount a volume for data persistence (database, config, projects)
      - autodidact_data:/app/data
      # Mount debug logs to host for easy access
      - ./debug-logs:/app/data/.autodidact
    environment:
      # Streamlit configuration
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      # Optional: Disable telemetry for privacy
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # Enable debug mode
      - AUTODIDACT_DEBUG=true
      # Enable more verbose Streamlit logging
      - STREAMLIT_LOGGER_LEVEL=debug
      - STREAMLIT_GLOBAL_DEVELOPMENT_MODE=true
    restart: unless-stopped
    # Override entrypoint to include debug flag
    entrypoint: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--", "--debug"]

volumes:
  autodidact_data:
    driver: local