services:
  autodidact:
    build: .
    ports:
      - "8501:8501"
    volumes:
      # Mount a volume for data persistence (database, config, projects)
      - autodidact_data:/app/data
    environment:
      # Streamlit configuration
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      # Optional: Disable telemetry for privacy
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped

volumes:
  autodidact_data:
    driver: local